import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const REGISTRY_DIR = path.join(process.cwd(), "registry");
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const KINDS = new Set(["game", "panel", "bundle"]);
const RUNTIMES = new Set(["swiftlys2", "counterstrikesharp"]);
const LAYOUTS = new Set(["csgo", "plugin"]);

export async function loadEntries() {
  const entries = [];

  for (const kind of await readdir(REGISTRY_DIR)) {
    const dir = path.join(REGISTRY_DIR, kind);
    let files;

    try {
      files = await readdir(dir);
    } catch {
      continue;
    }

    for (const file of files.filter((name) => name.endsWith(".json"))) {
      const filePath = path.join(dir, file);
      const raw = await readFile(filePath, "utf8");

      let entry;
      try {
        entry = JSON.parse(raw);
      } catch (error) {
        throw new Error(`${filePath}: not valid JSON — ${error.message}`);
      }

      entries.push({ entry, filePath, directory: kind, fileName: file });
    }
  }

  return entries;
}

export function validateEntry({ entry, filePath, directory, fileName }) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: ${message}`);

  for (const field of ["slug", "kind", "name", "author", "description"]) {
    if (typeof entry[field] !== "string" || entry[field].length === 0) {
      fail(`"${field}" is required`);
    }
  }

  if (entry.slug && !SLUG.test(entry.slug)) {
    fail(`slug "${entry.slug}" must be lowercase kebab-case`);
  }

  if (entry.slug && fileName !== `${entry.slug}.json`) {
    fail(`file must be named "${entry.slug}.json" to match its slug`);
  }

  if (entry.kind && !KINDS.has(entry.kind)) {
    fail(`kind "${entry.kind}" must be one of ${[...KINDS].join(", ")}`);
  }

  if (entry.kind && entry.kind !== directory) {
    fail(`lives in registry/${directory}/ but declares kind "${entry.kind}"`);
  }

  if (entry.versions) {
    fail(`"versions" is generated by CI from upstream releases — remove it`);
  }

  const needsVariants = entry.kind === "game" || entry.kind === "bundle";
  const variants = entry.variants ?? {};

  if (needsVariants && Object.keys(variants).length === 0) {
    fail(`kind "${entry.kind}" requires at least one entry under "variants"`);
  }

  for (const [runtime, variant] of Object.entries(variants)) {
    if (!RUNTIMES.has(runtime)) {
      fail(`unknown runtime "${runtime}"`);
      continue;
    }

    if (!/^[^/]+\/[^/]+$/.test(variant.repo ?? "")) {
      fail(`${runtime}.repo must be "owner/name"`);
    }

    if (typeof variant.asset !== "string" || variant.asset.length === 0) {
      fail(`${runtime}.asset is required`);
    }

    // Game servers are Linux containers. A Windows asset would unpack fine and
    // then never load, so it is rejected here rather than shipping a catalog
    // entry that quietly does nothing.
    if (/(^|[-_.])(win|win32|win64|windows|osx|macos|darwin)([-_.]|$|\*)/i.test(variant.asset ?? "")) {
      fail(
        `${runtime}.asset names a non-Linux platform; 5Stack game servers are Linux only`,
      );
    }

    const layout = variant.layout ?? "csgo";

    if (!LAYOUTS.has(layout)) {
      fail(`${runtime}.layout "${layout}" must be one of ${[...LAYOUTS].join(", ")}`);
    }

    if (layout === "plugin" && !variant.install_path) {
      fail(`${runtime}.install_path is required when layout is "plugin"`);
    }

    if (variant.install_path?.startsWith("/") || variant.install_path?.includes("..")) {
      fail(`${runtime}.install_path must be a relative path inside game/csgo`);
    }
  }

  const needsPanel = entry.kind === "panel" || entry.kind === "bundle";

  if (needsPanel && !entry.panel?.manifest_url) {
    fail(`kind "${entry.kind}" requires "panel.manifest_url"`);
  }

  // Without this the panel cannot tell an installed plugin from an available
  // one: an operator hosts the app themselves, so the URL they registered has
  // nothing in common with anything here. The route slug is fixed by the
  // plugin's own manifest, so it is the one stable thing to match on.
  if (needsPanel && !SLUG.test(entry.panel?.slug ?? "")) {
    fail(
      `kind "${entry.kind}" requires "panel.slug" — the slug from the plugin's 5stack-plugin.json`,
    );
  }

  if (entry.map_rotation) {
    problems.push(...validateMapRotation(entry, filePath));
  }

  if (entry.wiring) {
    if (entry.kind === "game") {
      fail(`"wiring" describes how a panel plugin configures a game plugin, so it does not belong on a game entry`);
    }

    if (!entry.wiring.provision?.endpoint) {
      fail(`"wiring.provision.endpoint" is required`);
    }

    if (!["mode_cfg", "plugin_config"].includes(entry.wiring.target)) {
      fail(`"wiring.target" must be "mode_cfg" or "plugin_config"`);
    }
  }

  return problems;
}

const MAP_ROTATION_DOCUMENT_TOKENS = new Set(["{{maps}}", "{{shuffle}}"]);
const MAP_ROTATION_MAP_TOKENS = new Set([
  "{{id}}",
  "{{name}}",
  "{{label}}",
  "{{workshop_id}}",
]);

function tokensIn(value) {
  if (typeof value === "string") {
    return value.match(/\{\{[^}]*\}\}/g) ?? [];
  }

  if (value && typeof value === "object") {
    return Object.values(value).flatMap(tokensIn);
  }

  return [];
}

function stringsIn(value) {
  if (typeof value === "string") {
    return [value];
  }

  if (value && typeof value === "object") {
    return Object.values(value).flatMap(stringsIn);
  }

  return [];
}

export function validateMapRotation(entry, filePath) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: map_rotation ${message}`);
  const { files, map } = entry.map_rotation;

  if (entry.kind === "panel") {
    fail(`only belongs on a game or bundle entry`);
  }

  if (!files || typeof files !== "object" || Object.keys(files).length === 0) {
    fail(`needs at least one file under "files"`);
    return problems;
  }

  if (!map || typeof map !== "object" || Array.isArray(map)) {
    fail(`needs a "map" object describing one entry`);
    return problems;
  }

  for (const [target, document] of Object.entries(files)) {
    if (target.startsWith("/") || target.includes("..")) {
      fail(`path "${target}" must be relative to game/csgo`);
    }

    if (!document || typeof document !== "object" || Array.isArray(document)) {
      fail(`"${target}" must map to a JSON object`);
      continue;
    }

    for (const token of tokensIn(document)) {
      if (!MAP_ROTATION_DOCUMENT_TOKENS.has(token)) {
        fail(`"${target}" uses ${token}; files may only use ${[...MAP_ROTATION_DOCUMENT_TOKENS].join(", ")}`);
      }
    }

    // {{maps}} is a list and {{shuffle}} a boolean; inside longer text either
    // would render as "[object Object]" or "true".
    for (const value of stringsIn(document)) {
      const embedded = tokensIn(value).filter((token) => MAP_ROTATION_DOCUMENT_TOKENS.has(token));

      if (embedded.length > 0 && value !== embedded[0]) {
        fail(`"${target}" must use ${embedded.join(", ")} as a whole value, not inside "${value}"`);
      }
    }
  }

  if (!Object.values(files).some((document) => tokensIn(document).includes("{{maps}}"))) {
    fail(`never writes {{maps}}, so the rotation would go nowhere`);
  }

  for (const token of tokensIn(map)) {
    if (!MAP_ROTATION_MAP_TOKENS.has(token)) {
      fail(`"map" uses ${token}; entries may only use ${[...MAP_ROTATION_MAP_TOKENS].join(", ")}`);
    }
  }

  return problems;
}

export async function validateAll() {
  const entries = await loadEntries();
  const problems = entries.flatMap(validateEntry);
  const seen = new Map();

  for (const { entry, filePath } of entries) {
    if (seen.has(entry.slug)) {
      problems.push(`${filePath}: slug "${entry.slug}" already used by ${seen.get(entry.slug)}`);
    }
    seen.set(entry.slug, filePath);
  }

  // A dangling pairs_with renders as a broken link in the directory.
  for (const { entry, filePath } of entries) {
    for (const slug of entry.pairs_with ?? []) {
      if (!seen.has(slug)) {
        problems.push(`${filePath}: pairs_with names "${slug}", which is not in the registry`);
      }
    }
  }

  return { entries, problems };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { entries, problems } = await validateAll();

  for (const problem of problems) {
    console.error(`  ${problem}`);
  }

  if (problems.length > 0) {
    console.error(`\n${problems.length} problem(s) in ${entries.length} entries`);
    process.exit(1);
  }

  console.log(`${entries.length} entries valid`);
}
