import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const REGISTRY_DIR = path.join(process.cwd(), "registry");
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const KINDS = new Set(["game", "panel", "bundle"]);
const RUNTIMES = new Set(["swiftlys2", "counterstrikesharp"]);
const LAYOUTS = new Set(["csgo", "plugin"]);

export async function loadEntries() {
  const entries = [];

  for (const kind of await readdir(REGISTRY_DIR)) {
    const dir = path.join(REGISTRY_DIR, kind);
    let files;

    try {
      files = await readdir(dir);
    } catch {
      continue;
    }

    for (const file of files.filter((name) => name.endsWith(".json"))) {
      const filePath = path.join(dir, file);
      const raw = await readFile(filePath, "utf8");

      let entry;
      try {
        entry = JSON.parse(raw);
      } catch (error) {
        throw new Error(`${filePath}: not valid JSON — ${error.message}`);
      }

      entries.push({ entry, filePath, directory: kind, fileName: file });
    }
  }

  return entries;
}

export function validateEntry({ entry, filePath, directory, fileName }) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: ${message}`);

  for (const field of ["slug", "kind", "name", "author", "description"]) {
    if (typeof entry[field] !== "string" || entry[field].length === 0) {
      fail(`"${field}" is required`);
    }
  }

  if (entry.slug && !SLUG.test(entry.slug)) {
    fail(`slug "${entry.slug}" must be lowercase kebab-case`);
  }

  if (entry.slug && fileName !== `${entry.slug}.json`) {
    fail(`file must be named "${entry.slug}.json" to match its slug`);
  }

  if (entry.kind && !KINDS.has(entry.kind)) {
    fail(`kind "${entry.kind}" must be one of ${[...KINDS].join(", ")}`);
  }

  if (entry.kind && entry.kind !== directory) {
    fail(`lives in registry/${directory}/ but declares kind "${entry.kind}"`);
  }

  if (entry.versions) {
    fail(`"versions" is generated by CI from upstream releases — remove it`);
  }

  const needsVariants = entry.kind === "game" || entry.kind === "bundle";
  const variants = entry.variants ?? {};

  if (needsVariants && Object.keys(variants).length === 0) {
    fail(`kind "${entry.kind}" requires at least one entry under "variants"`);
  }

  for (const [runtime, variant] of Object.entries(variants)) {
    if (!RUNTIMES.has(runtime)) {
      fail(`unknown runtime "${runtime}"`);
      continue;
    }

    if (!/^[^/]+\/[^/]+$/.test(variant.repo ?? "")) {
      fail(`${runtime}.repo must be "owner/name"`);
    }

    if (typeof variant.asset !== "string" || variant.asset.length === 0) {
      fail(`${runtime}.asset is required`);
    }

    // Game servers are Linux containers. A Windows asset would unpack fine and
    // then never load, so it is rejected here rather than shipping a catalog
    // entry that quietly does nothing.
    if (/(^|[-_.])(win|win32|win64|windows|osx|macos|darwin)([-_.]|$|\*)/i.test(variant.asset ?? "")) {
      fail(
        `${runtime}.asset names a non-Linux platform; 5Stack game servers are Linux only`,
      );
    }

    const layout = variant.layout ?? "csgo";

    if (!LAYOUTS.has(layout)) {
      fail(`${runtime}.layout "${layout}" must be one of ${[...LAYOUTS].join(", ")}`);
    }

    if (layout === "plugin" && !variant.install_path) {
      fail(`${runtime}.install_path is required when layout is "plugin"`);
    }

    if (variant.install_path?.startsWith("/") || variant.install_path?.includes("..")) {
      fail(`${runtime}.install_path must be a relative path inside game/csgo`);
    }
  }

  const needsPanel = entry.kind === "panel" || entry.kind === "bundle";

  if (needsPanel && !entry.panel?.manifest_url) {
    fail(`kind "${entry.kind}" requires "panel.manifest_url"`);
  }

  // Without this the panel cannot tell an installed plugin from an available
  // one: an operator hosts the app themselves, so the URL they registered has
  // nothing in common with anything here. The route slug is fixed by the
  // plugin's own manifest, so it is the one stable thing to match on.
  if (needsPanel && !SLUG.test(entry.panel?.slug ?? "")) {
    fail(
      `kind "${entry.kind}" requires "panel.slug" — the slug from the plugin's 5stack-plugin.json`,
    );
  }

  if (entry.map_rotation) {
    problems.push(...validateMapRotation(entry, filePath));
  }

  problems.push(...validateConfig(entry, filePath));
  problems.push(...validateWorkshopAddons(entry, filePath));

  if (entry.wiring) {
    if (entry.kind === "game") {
      fail(`"wiring" describes how a panel plugin configures a game plugin, so it does not belong on a game entry`);
    }

    if (!entry.wiring.provision?.endpoint) {
      fail(`"wiring.provision.endpoint" is required`);
    }

    if (!["mode_cfg", "plugin_config"].includes(entry.wiring.target)) {
      fail(`"wiring.target" must be "mode_cfg" or "plugin_config"`);
    }
  }

  return problems;
}

const MAP_ROTATION_DOCUMENT_TOKENS = new Set(["{{maps}}", "{{shuffle}}"]);
const MAP_ROTATION_MAP_TOKENS = new Set([
  "{{id}}",
  "{{name}}",
  "{{label}}",
  "{{workshop_id}}",
]);

function tokensIn(value) {
  if (typeof value === "string") {
    return value.match(/\{\{[^}]*\}\}/g) ?? [];
  }

  if (value && typeof value === "object") {
    return Object.values(value).flatMap(tokensIn);
  }

  return [];
}

function stringsIn(value) {
  if (typeof value === "string") {
    return [value];
  }

  if (value && typeof value === "object") {
    return Object.values(value).flatMap(stringsIn);
  }

  return [];
}

export function validateMapRotation(entry, filePath) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: map_rotation ${message}`);
  const { files, map } = entry.map_rotation;

  if (entry.kind === "panel") {
    fail(`only belongs on a game or bundle entry`);
  }

  if (!files || typeof files !== "object" || Object.keys(files).length === 0) {
    fail(`needs at least one file under "files"`);
    return problems;
  }

  if (!map || typeof map !== "object" || Array.isArray(map)) {
    fail(`needs a "map" object describing one entry`);
    return problems;
  }

  for (const [target, document] of Object.entries(files)) {
    if (target.startsWith("/") || target.includes("..")) {
      fail(`path "${target}" must be relative to game/csgo`);
    }

    if (!document || typeof document !== "object" || Array.isArray(document)) {
      fail(`"${target}" must map to a JSON object`);
      continue;
    }

    for (const token of tokensIn(document)) {
      if (!MAP_ROTATION_DOCUMENT_TOKENS.has(token)) {
        fail(`"${target}" uses ${token}; files may only use ${[...MAP_ROTATION_DOCUMENT_TOKENS].join(", ")}`);
      }
    }

    // {{maps}} is a list and {{shuffle}} a boolean; inside longer text either
    // would render as "[object Object]" or "true".
    for (const value of stringsIn(document)) {
      const embedded = tokensIn(value).filter((token) => MAP_ROTATION_DOCUMENT_TOKENS.has(token));

      if (embedded.length > 0 && value !== embedded[0]) {
        fail(`"${target}" must use ${embedded.join(", ")} as a whole value, not inside "${value}"`);
      }
    }
  }

  if (!Object.values(files).some((document) => tokensIn(document).includes("{{maps}}"))) {
    fail(`never writes {{maps}}, so the rotation would go nowhere`);
  }

  for (const token of tokensIn(map)) {
    if (!MAP_ROTATION_MAP_TOKENS.has(token)) {
      fail(`"map" uses ${token}; entries may only use ${[...MAP_ROTATION_MAP_TOKENS].join(", ")}`);
    }
  }

  return problems;
}

const CVAR = /^[A-Za-z0-9_.]+$/;

export function validateConfig(entry, filePath) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: ${message}`);

  for (const field of ["cvars", "forced_cvars"]) {
    if (entry[field] === undefined) {
      continue;
    }

    if (!Array.isArray(entry[field])) {
      fail(`"${field}" must be a list of console variable names`);
      continue;
    }

    for (const name of entry[field]) {
      if (typeof name !== "string" || !CVAR.test(name)) {
        fail(`"${field}" has ${JSON.stringify(name)}, which is not a console variable name`);
      }
    }
  }

  const path = entry.config_path;

  if (path !== undefined && (typeof path !== "string" || path.startsWith("/") || path.includes(".."))) {
    fail(`"config_path" must be a relative path inside game/csgo`);
  }

  for (const field of ["config_schema", "config_default", "config_cvar", "config_shipped"]) {
    if (entry[field] !== undefined && !path) {
      fail(`"${field}" describes the config file, so it needs "config_path"`);
    }
  }

  for (const field of ["path", "repo_path"]) {
    const shipped = entry.config_shipped?.[field];

    if (shipped !== undefined && (typeof shipped !== "string" || shipped.startsWith("/") || shipped.includes(".."))) {
      fail(`"config_shipped.${field}" must be a relative path`);
    }
  }

  if (
    entry.config_shipped !== undefined &&
    (typeof entry.config_shipped !== "object" || entry.config_shipped === null || Array.isArray(entry.config_shipped))
  ) {
    fail(`"config_shipped" must be an object with "path" and "repo_path"`);
  }

  if (entry.config_cvar !== undefined && (typeof entry.config_cvar !== "string" || !CVAR.test(entry.config_cvar))) {
    fail(`"config_cvar" must be a console variable name`);
  }

  if (entry.config_default !== undefined && entry.config_schema) {
    for (const problem of schemaProblems(entry.config_schema, entry.config_default, "config_default")) {
      fail(problem);
    }
  }

  return problems;
}

const WORKSHOP_ID = /^[0-9]+$/;

// AddonsManager validates its config when it starts, so one id that is not a
// bare number takes it down on every server running the plugin -- and the
// addons with it. Each is held to that here instead.
export function validateWorkshopAddons(entry, filePath) {
  const problems = [];
  const fail = (message) => problems.push(`${filePath}: ${message}`);
  const addons = entry.workshop_addons;

  if (addons === undefined) {
    return problems;
  }

  if (!Array.isArray(addons)) {
    fail(`"workshop_addons" must be a list of workshop ids`);
    return problems;
  }

  if (entry.kind === "panel") {
    fail(`"workshop_addons" only belongs on a game or bundle entry`);
  }

  // The only AddonsManager 5Stack ships is in the SwiftlyS2 image. A plugin
  // with no SwiftlyS2 build would list addons no server ever serves.
  if (!entry.variants?.swiftlys2) {
    fail(`"workshop_addons" are served by AddonsManager, which 5Stack only ships for SwiftlyS2, so the entry needs a swiftlys2 variant`);
  }

  const seen = new Set();

  for (const id of addons) {
    if (typeof id !== "string" || !WORKSHOP_ID.test(id)) {
      fail(`"workshop_addons" has ${JSON.stringify(id)}; a workshop id is a string of digits, e.g. "3791548068"`);
      continue;
    }

    if (seen.has(id)) {
      fail(`"workshop_addons" lists ${id} more than once`);
    }

    seen.add(id);
  }

  return problems;
}

// The subset of JSON Schema the panel's form understands. A default the form
// cannot render is a broken editor, so it is held to the same rules.
export function schemaProblems(schema, value, at) {
  const problems = [];
  const type = schema?.type;

  const matches =
    type === undefined ||
    (type === "array" && Array.isArray(value)) ||
    (type === "object" && value !== null && typeof value === "object" && !Array.isArray(value)) ||
    (type === "string" && typeof value === "string") ||
    (type === "boolean" && typeof value === "boolean") ||
    (type === "number" && typeof value === "number") ||
    (type === "integer" && Number.isInteger(value));

  if (!matches) {
    return [`${at} should be ${type}, got ${JSON.stringify(value)}`];
  }

  if (schema.enum && !schema.enum.includes(value)) {
    problems.push(`${at} is ${JSON.stringify(value)}, which is not one of its options`);
  }

  if (typeof value === "number") {
    if (schema.minimum !== undefined && value < schema.minimum) {
      problems.push(`${at} is below its minimum of ${schema.minimum}`);
    }

    if (schema.maximum !== undefined && value > schema.maximum) {
      problems.push(`${at} is above its maximum of ${schema.maximum}`);
    }
  }

  if (type === "array") {
    // A duplicate is not a style problem: the Deathmatch plugin keys a mode's
    // weapons by item id and drops the whole file on the second one.
    if (schema.uniqueItems) {
      const seen = new Set();

      for (const item of value) {
        const key = JSON.stringify(item);

        if (seen.has(key)) {
          problems.push(`${at} lists ${key} more than once`);
        }

        seen.add(key);
      }
    }

    value.forEach((item, index) => {
      problems.push(...schemaProblems(schema.items ?? {}, item, `${at}[${index}]`));
    });
  }

  if (type === "object") {
    for (const key of schema.required ?? []) {
      if (value[key] === undefined || value[key] === "") {
        problems.push(`${at}.${key} is required`);
      }
    }

    for (const [key, item] of Object.entries(value)) {
      const property = schema.properties?.[key];

      if (!property) {
        problems.push(`${at}.${key} is not described by the schema`);
        continue;
      }

      problems.push(...schemaProblems(property, item, `${at}.${key}`));
    }
  }

  return problems;
}

export async function validateAll() {
  const entries = await loadEntries();
  const problems = entries.flatMap(validateEntry);
  const seen = new Map();

  for (const { entry, filePath } of entries) {
    if (seen.has(entry.slug)) {
      problems.push(`${filePath}: slug "${entry.slug}" already used by ${seen.get(entry.slug)}`);
    }
    seen.set(entry.slug, filePath);
  }

  // A dangling pairs_with renders as a broken link in the directory.
  for (const { entry, filePath } of entries) {
    for (const slug of entry.pairs_with ?? []) {
      if (!seen.has(slug)) {
        problems.push(`${filePath}: pairs_with names "${slug}", which is not in the registry`);
      }
    }
  }

  return { entries, problems };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { entries, problems } = await validateAll();

  for (const problem of problems) {
    console.error(`  ${problem}`);
  }

  if (problems.length > 0) {
    console.error(`\n${problems.length} problem(s) in ${entries.length} entries`);
    process.exit(1);
  }

  console.log(`${entries.length} entries valid`);
}
